//{{NO_DEPENDENCIES}}
// Microsoft eMbedded Visual C++ generated include file.
// Used by RichesseGPS.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_BROWSE                      101
#define IDD_SETUP_GENERAL               102
#define IDD_SETUP_GPS                   103
#define IDD_INFO                        104
#define IDD_ADD                         105
#define IDD_ADD_NOTES                   106
#define IDD_LICENSE                     107
#define IDD_CREDITS                     108
#define IDR_MAINFRAME                   128
#define IDR_CANCEL                      130
#define IDR_EDIT                        131
#define IDB_DIRS_HI                     133
#define IDB_CACHE_HI                    134
#define IDB_CACHE                       135
#define IDB_DIRS                        136
#define IDD_POI_MAN                     137
#define IDR_POI_MAN                     138
#define IDD_RADAR                       138
#define IDR_POI_MAN_CTX                 139
#define IDD_DOWNLOAD                    139
#define IDB_POI_STATUS_HI               140
#define IDR_WAYPOINT_CTX                140
#define IDB_POI_STATUS                  141
#define IDR_IMPORT                      142
#define IDR_EXPORT                      143
#define IDR_INFO                        144
#define IDR_ADD                         145
#define IDB_BTN_ADD_HI                  146
#define IDR_RADAR                       146
#define IDB_BTN_ADD                     147
#define IDB_BTN_NOTES                   148
#define IDB_BTN_NOTES_HI                149
#define IDB_BTN_COMPASS                 150
#define IDB_BTN_COMPASS_HI              151
#define IDB_BTN_INFO_HI                 152
#define IDB_BTN_INFO                    153
#define IDS_MYDEVICE                    200
#define IDS_NOT_FILE                    201
#define IDS_LOCATION_NOT_DIR            202
#define IDS_DIRECTORY_NOT_CREATED       203
#define IDS_NO_ITEMS_TO_DISPLAY         204
#define IDS_OPTIONS                     205
#define IDS_METRIC                      206
#define IDS_ENGLISH                     207
#define IDS_GPS_INFO                    208
#define IDS_SATELLITES                  209
#define IDS_RUNNING                     210
#define IDS_UNKNOWN                     211
#define IDS_NOT_RUNNING                 212
#define IDS_GPS_ON                      213
#define IDS_GPS_OFF                     214
#define IDS_GPS_CONNECT_FAILED          215
#define IDS_FILE_TO_IMPORT              216
#define IDS_SELECT_LOCATION             217
#define IDS_NAME                        218
#define IDS_IMPORT_FAILED               219
#define IDS_EXPORT_UNSUCCESSFUL         220
#define IDS_WAYPOINT_INFO_ID            221
#define IDS_WAYPOINT_INFO               222
#define IDS_ARE_YOU_SERIOUS             223
#define IDS_OVERWRITE_FILE              224
#define IDS_CANNOT_CREATE_FILE_EXPORT   225
#define IDS_EXPORT_SUCCESSFUL           226
#define IDS_TRADITIONAL                 227
#define IDS_MULTICACHE                  228
#define IDS_LETTERBOX                   229
#define IDS_EARTHCACHE                  230
#define IDS_EVENTCACHE                  231
#define IDS_MYSTERYCACHE                232
#define IDS_MY_POI                      233
#define IDS_ADD_WAYPOINT                234
#define IDS_DISTANCE                    235
#define IDS_COPY_STR                    236
#define IDS_NO_WAYPOINT_SELECTED        237
#define IDS_VIRTUAL                     238
#define IDS_ABOUT                       239
#define IDC_HOMEPAGE                    1000
#define IDC_PATH                        1001
#define IDC_DIRS                        1002
#define IDC_C_COORDS                    1003
#define IDC_COORDS                      1004
#define IDC_C_SUSPEND_MODE              1005
#define IDC_PREVENT_SUSPEND             1006
#define IDC_C_GPS_CONN                  1007
#define IDC_UNITS                       1007
#define IDC_PORT                        1008
#define IDC_BAUD_RATE                   1009
#define IDC_AUTO_CONNECT                1010
#define IDC_RECONNECT                   1011
#define IDC_AUTODETECT                  1012
#define IDC_C_POSITION                  1013
#define IDC_LATITUDE                    1014
#define IDC_LONGITUDE                   1015
#define IDC_ALTITUDE                    1016
#define IDC_SAT_CNT                     1017
#define IDC_C_SATELLITES                1018
#define IDC_SATELLITES                  1019
#define IDC_STATUS                      1020
#define IDC_WAYPOINT                    1021
#define IDC_COMPASS                     1022
#define IDC_LBL_DIST                    1023
#define IDC_LBL_ALT                     1024
#define IDC_DISTANCE                    1025
#define IDC_LBL_SPEED                   1026
#define IDC_SPEED                       1027
#define IDC_POIS                        1028
#define IDC_NAME                        1029
#define IDC_TYPE                        1030
#define IDC_LAT_DIR                     1031
#define IDC_LAT_DEG                     1032
#define IDC_LAT_MIN                     1033
#define IDC_LAT_SEC                     1034
#define IDC_LONG_DIR                    1035
#define IDC_LONG_DEG                    1036
#define IDC_LONG_MIN                    1037
#define IDC_LONG_SEC                    1038
#define IDC_DESCRIPTION                 1039
#define IDC_ADD_BTN                     1040
#define IDC_COMPASS_BTN                 1041
#define IDC_NOTES_BTN                   1042
#define IDC_NOTES                       1043
#define IDC_INFO_BTN                    1044
#define IDC_INFO                        1045
#define IDC_COMPLETED                   1046
#define IDC_COMPLETED_LBL               1047
#define IDC_ITEMS                       1048
#define IDC_PROGRESS                    1049
#define IDC_HOMEPAGE_LINK               1050
#define IDC_LICENSE                     1051
#define IDC_CREDITS                     1052
#define ID_MENU_OPTIONS                 32772
#define IDS_CAP_CANCEL                  32774
#define ID_NEW_FOLDER                   32775
#define ID_GPS_ON                       32776
#define ID_MENU_POIMANAGER              32777
#define ID_MENU_GPSINFO                 32778
#define IDS_CAP_MENUITEM32780           32781
#define ID_NAVIGATE                     32782
#define IDS_CAP_NAVIGATE                32784
#define ID_MENU                         32785
#define IDS_CAP_MENU                    32787
#define ID_MENU_ADDPOI                  32788
#define ID_MENU_EDIT                    32789
#define ID_MENU_EXPORT                  32790
#define ID_MENU_IMPORT                  32791
#define ID_MENU_DELETE                  32792
#define ID_POI                          32794
#define IDS_CAP_POI                     32796
#define ID_POI_SELECTALL                32797
#define ID_POI_SORTBY_NAME              32798
#define ID_POI_SORTBY_STATUS            32799
#define ID_POI_SORTBY_CACHETYPE         32800
#define ID_POI_SORTBY_ASCENDING         32801
#define ID_POI_SORTBY_DESCENDING        32802
#define ID_POI_MARKAS_NOTCOMPLETED      32803
#define ID_POI_MARKAS_COMPLETED         32804
#define ID_POI_MARKAS_NOTFOUND          32805
#define ID_IMPORT                       32806
#define IDS_CAP_IMPORT                  32808
#define ID_EXPORT                       32810
#define IDS_CAP_EXPORT                  32812
#define ID_SAVE                         32814
#define IDS_CAP_SAVE                    32816
#define ID_ADD                          32818
#define IDS_CAP_ADD                     32820
#define ID_CANCEL                       32821
#define ID_MENU_RADAR                   32823
#define IDS_CAP_CLOSE                   32825
#define ID_COPY_WAYPOINT                32826
#define ID_COPY_LONGITUDE               32827
#define ID_COPY_LATITUDE                32828
#define ID_MENU_EXPORT_KML              32829
#define ID_MENU_DOWNLOADINFO            32830
#define ID_MENU_COMPASS_VIEW			32840
#define ID_MENU_NOTEPAD_VIEW			32841
#define ID_MENU_POIINFO_VIEW			32842
#define ID_MENU_ADD_NEW_POI				32843

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        154
#define _APS_NEXT_COMMAND_VALUE         32844
#define _APS_NEXT_CONTROL_VALUE         1053
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
